const time = [
  {
    "1": "January",
    "2": "February",
    "3": "March",
    "4": "April",
    "5": "May",
    "6": "June",
    "7": "July",
    "8": "August",
    "9": "September",
    "10": "October",
    "11": "November",
    "12": "December"
  },
 {
    "1": "Hounvar",
    "2": "Pedrvar",
    "3": "Mard",
    "4": "Abril",
    "5": "Mayis",
    "6": "Hoonis",
    "7": "Hoolis",
    "8": "Ocosdos",
    "9": "Sebdemper",
    "10": "Hokdemper",
    "11": "Noyemper",
    "12": "Tegdemper"
  },
  {
    "1": "Januarie",
    "2": "Februarie",
    "3": "Maart",
    "4": "April",
    "5": "Mei",
    "6": "Junie",
    "7": "Julie",
    "8": "Augustus",
    "9": "September",
    "10": "Oktober",
    "11": "November",
    "12": "Desember"
  },
  {
    "1": "Студзень",
    "2": "Люты",
    "3": "Сакавік",
    "4": "Красавік",
    "5": "Травень",
    "6": "Чэрвень",
    "7": "Ліпень",
    "8": "Жнівень",
    "9": "Верасень",
    "10": "Кастрычнік",
    "11": "Лістапад",
    "12": "Сьнежань"
  },
  {
    "1": "януари",
    "2": "февруар",
    "3": "март",
    "4": "април",
    "5": "май",
    "6": "юни",
    "7": "юли",
    "8": "август",
    "9": "септември",
    "10": "октомври",
    "11": "ноември",
    "12": "декември"
  },
  {
    "1": "ianuari",
    "2": "fevruari",
    "3": "mart",
    "4": "april",
    "5": "maj",
    "6": "juni",
    "7": "juli",
    "8": "avgust",
    "9": "septemvri",
    "10": "oktomvri",
    "11": "noemvri",
    "12": "dekemvri"
  },
  {
    "1": "január",
    "2": "február",
    "3": "március",
    "4": "április",
    "5": "május",
    "6": "június",
    "7": "július",
    "8": "augusztus",
    "9": "szeptember",
    "10": "október",
    "11": "november",
    "12": "december"
  },
  {
    "1": "januari",
    "2": "februari",
    "3": "maart",
    "4": "april",
    "5": "mei",
    "6": "juni",
    "7": "juli",
    "8": "augustus",
    "9": "september",
    "10": "oktober",
    "11": "november",
    "12": "december"
  },
  {
    "1": "Ιανουάριος",
    "2": "Φεβρουάριος",
    "3": "Μάρτιος",
    "4": "Απρίλιος",
    "5": "Μάιος",
    "6": "Ιούνιος",
    "7": "Ιούλιος",
    "8": "Αύγουστος",
    "9": "Σεπτέμβριος",
    "10": "Οκτώβριος",
    "11": "Νοέμβριος",
    "12": "Δεκέμβριος"
  },
  {
    "1": "Ianouários",
    "2": "Febrouários",
    "3": "Mártios",
    "4": "Aprílios",
    "5": "Máios",
    "6": "Ioúnios",
    "7": "Ioúlios",
    "8": "Aúgoustos",
    "9": "Septémbrios",
    "10": "Oktṓbrios",
    "11": "Noémbrios",
    "12": "Dekémbrios"
  },
  {
    "1": "Januar",
    "2": "Februar",
    "3": "Marts",
    "4": "April",
    "5": "Maj",
    "6": "Juni",
    "7": "Juli",
    "8": "August",
    "9": "September",
    "10": "Oktober",
    "11": "November",
    "12": "December"
  },
  {
    "1": "Januari",
    "2": "Februari",
    "3": "Maret",
    "4": "April",
    "5": "Mei",
    "6": "Juni",
    "7": "Juli",
    "8": "Agustus",
    "9": "September",
    "10": "Oktober",
    "11": "November",
    "12": "Desember"
  },
  {
    "1": "janúar",
    "2": "febrúar",
    "3": "mars",
    "4": "apríl",
    "5": "maí",
    "6": "júní",
    "7": "júlí",
    "8": "ágúst",
    "9": "september",
    "10": "október",
    "11": "nóvember",
    "12": "desember"
  }, {
    "1": "enero",
    "2": "febrer",
    "3": "marzo",
    "4": "abril",
    "5": "mayo",
    "6": "junio",
    "7": "julio",
    "8": "agosto",
    "9": "septiembre",
    "10": "octubre",
    "11": "noviembre",
    "12": "diciembre"
  },
  {
    "1": "gennaio",
    "2": "febbraio",
    "3": "marzo",
    "4": "aprile",
    "5": "maggio",
    "6": "giugno",
    "7": "luglio",
    "8": "agosto",
    "9": "settembre",
    "10": "ottobre",
    "11": "novembre",
    "12": "dicembre"
  },
  {
    "1": "janvāris",
    "2": "februāris",
    "3": "marts",
    "4": "aprīlis",
    "5": "maijs",
    "6": "jūnijs",
    "7": "jūlijs",
    "8": "augusts",
    "9": "septembris",
    "10": "oktobris",
    "11": "novembris",
    "12": "decembris"
  },
  {
    "1": "sausis",
    "2": "vasaris",
    "3": "kovas",
    "4": "balandis",
    "5": "gegužė",
    "6": "birželis",
    "7": "liepa",
    "8": "rugpjūtis",
    "9": "rusėjis",
    "10": "spalis",
    "11": "lapkritis",
    "12": "gruodis"
  },
  {
    "1": "Januar",
    "2": "Februar",
    "3": "März",
    "4": "April",
    "5": "Mai",
    "6": "Juni",
    "7": "Juli",
    "8": "August",
    "9": "September",
    "10": "Oktober",
    "11": "November",
    "12": "Dezember"
  },
  {
    "1": "januar",
    "2": "februar",
    "3": "mars",
    "4": "april",
    "5": "mai",
    "6": "juni",
    "7": "juli",
    "8": "august",
    "9": "september",
    "10": "oktober",
    "11": "november",
    "12": "desember"
  },
  {
    "1": "styczeń",
    "2": "luty",
    "3": "marzec",
    "4": "kwiecień",
    "5": "maj",
    "6": "czerwiec",
    "7": "lipiec",
    "8": "sierpień",
    "9": "wrzesień",
    "10": "październik",
    "11": "listopad",
    "12": "grudzień"
  },
  {
    "1": "janeiro",
    "2": "fevereir",
    "3": "março",
    "4": "abril",
    "5": "maio",
    "6": "junho",
    "7": "julho",
    "8": "agosto",
    "9": "setembro",
    "10": "outubro",
    "11": "novembro",
    "12": "dezembro"
  },
  {
    "1": "ianuarie",
    "2": "februarie",
    "3": "martie",
    "4": "aprilie",
    "5": "mai",
    "6": "iunie",
    "7": "iulie",
    "8": "august",
    "9": "septembrie",
    "10": "octombrie",
    "11": "noiembrie",
    "12": "decembrie"
  },
  {
    "1": "Јануар",
    "2": "Фебруар",
    "3": "Март",
    "4": "Април",
    "5": "Мај",
    "6": "Јуни",
    "7": "Јули",
    "8": "Август",
    "9": "Септембар",
    "10": "Октобар",
    "11": "Новембар",
    "12": "Децембар"
  },
  {
    "1": "január",
    "2": "február",
    "3": "marec",
    "4": "apríl",
    "5": "máj",
    "6": "jún",
    "7": "júl",
    "8": "august",
    "9": "september",
    "10": "október",
    "11": "november",
    "12": "december"
  },
  {
    "1": "januar",
    "2": "februar",
    "3": "marec",
    "4": "april",
    "5": "maj",
    "6": "junij",
    "7": "julij",
    "8": "avgust",
    "9": "september",
    "10": "oktober",
    "11": "november",
    "12": "december"
  },
  {
    "1": "Ocak",
    "2": "Şubat",
    "3": "Mart",
    "4": "Nisan",
    "5": "Mayıs",
    "6": "Haziran",
    "7": "Temmuz",
    "8": "Ağustos",
    "9": "Eylül",
    "10": "Ekim",
    "11": "Kasım",
    "12": "Aralık"
  },
  {
    "1": "січень",
    "2": "лютий",
    "3": "березень",
    "4": "квітень",
    "5": "травень",
    "6": "червень",
    "7": "липень",
    "8": "серпень",
    "9": "вересень",
    "10": "жовтень",
    "11": "листопад",
    "12": "грудень"
  },
  {
    "1": "tammikuu",
    "2": "helmikuu",
    "3": "maaliskuu",
    "4": "huhtikuu",
    "5": "toukokuu",
    "6": "kesäkuu",
    "7": "heinäkuu",
    "8": "elokuu",
    "9": "syyskuu",
    "10": "lokakuu",
    "11": "marraskuu",
    "12": "joulukuu"
  },
  {
    "1": "janvier",
    "2": "février",
    "3": "mars",
    "4": "avril",
    "5": "mai",
    "6": "juin",
    "7": "juillet",
    "8": "août",
    "9": "septembre",
    "10": "octobre",
    "11": "novembre",
    "12": "décembre"
  },
  {
    "1": "leden",
    "2": "únor",
    "3": "březen",
    "4": "duben",
    "5": "květen",
    "6": "červen",
    "7": "červenec",
    "8": "srpen",
    "9": "září",
    "10": "říjen",
    "11": "listopad",
    "12": "prosinec"
  },
  {
    "1": "januari",
    "2": "februari",
    "3": "mars",
    "4": "april",
    "5": "maj",
    "6": "juni",
    "7": "juli",
    "8": "augusti",
    "9": "september",
    "10": "oktober",
    "11": "november",
    "12": "december"
  },
  {
    "1": "jaanuar",
    "2": "veebruar",
    "3": "märts",
    "4": "aprill",
    "5": "mai",
    "6": "juuni",
    "7": "juuli",
    "8": "august",
    "9": "september",
    "10": "oktoober",
    "11": "november",
    "12": "detsember"
  },
  {
    "1": "יָנוּאַר",
    "2": "פֶבּרוּאַר",
    "3": "מֶרץ",
    "4": "אַפּרִיל",
    "5": "מַאי",
    "6": "יוּנִי",
    "7": "יוּלִי",
    "8": "אוֹגוּסט",
    "9": "סֶפּטֶמבֶּר",
    "10": "אוֹקטוֹבֶּר",
    "11": "נוֹבֶמבֶּר",
    "12": "דֶצֶמבֶּר"
  },
  {
    "1": "Jan",
    "2": "Feb",
    "3": "Mar",
    "4": "Apr",
    "5": "May",
    "6": "Jun",
    "7": "Jul",
    "8": "Aug",
    "9": "Sep",
    "10": "Oct",
    "11": "Nov",
    "12": "Dec"
  },
  {
    "1": "Hou",
    "2": "Ped",
    "3": "Mar",
    "4": "Abr",
    "5": "May",
    "6": "Hoon",
    "7": "Hool",
    "8": "Oco",
    "9": "Seb",
    "10": "Hok",
    "11": "Noy",
    "12": "Teg"
  },
  {
    "1": "Jan",
    "2": "Feb",
    "3": "Maa",
    "4": "Apr",
    "5": "Mei",
    "6": "Jun",
    "7": "Jul",
    "8": "Aug",
    "9": "Sep",
    "10": "Okt",
    "11": "Nov",
    "12": "Des"
  },
  {
    "1": "Сту",
    "2": "Лют",
    "3": "Сак",
    "4": "Кра",
    "5": "Тра",
    "6": "Чэр",
    "7": "Ліп",
    "8": "Жні",
    "9": "Вер",
    "10": "Кас",
    "11": "Ліс",
    "12": "Сьн"
  },
  {
    "1": "яну",
    "2": "фев",
    "3": "мар",
    "4": "апр",
    "5": "май",
    "6": "юни",
    "7": "юли",
    "8": "авг",
    "9": "сеп",
    "10": "окт",
    "11": "ное",
    "12": "дек"
  },
  {
    "1": "ian",
    "2": "fev",
    "3": "mar",
    "4": "apr",
    "5": "maj",
    "6": "jun",
    "7": "jul",
    "8": "avg",
    "9": "sep",
    "10": "okt",
    "11": "noe",
    "12": "dek"
  },
  {
    "1": "jan",
    "2": "feb",
    "3": "már",
    "4": "ápr",
    "5": "máj",
    "6": "jún",
    "7": "júl",
    "8": "aug",
    "9": "sze",
    "10": "okt",
    "11": "nov",
    "12": "dec"
  },
  {
    "1": "jan",
    "2": "feb",
    "3": "maa",
    "4": "apr",
    "5": "mei",
    "6": "jun",
    "7": "jul",
    "8": "aug",
    "9": "sep",
    "10": "okt",
    "11": "nov",
    "12": "dec"
  },
  {
    "1": "Ιαν",
    "2": "Φεβ",
    "3": "Μάρ",
    "4": "Απρ",
    "5": "Μάι",
    "6": "Ιού",
    "7": "Ιού",
    "8": "Αύγ",
    "9": "Σεπ",
    "10": "Οκτ",
    "11": "Νοέ",
    "12": "Δεκ"
  },
  {
    "1": "Ian",
    "2": "Feb",
    "3": "Már",
    "4": "Apr",
    "5": "Mái",
    "6": "Ioú",
    "7": "Ioú",
    "8": "Aúg",
    "9": "Sep",
    "10": "Okt",
    "11": "Noé",
    "12": "Dek"
  },
  {
    "1": "Jan",
    "2": "Feb",
    "3": "Mar",
    "4": "Apr",
    "5": "Maj",
    "6": "Jun",
    "7": "Jul",
    "8": "Aug",
    "9": "Sep",
    "10": "Okt",
    "11": "Nov",
    "12": "Dec"
  },
  {
    "1": "Jan",
    "2": "Feb",
    "3": "Mar",
    "4": "Apr",
    "5": "Mei",
    "6": "Jun",
    "7": "Jul",
    "8": "Agu",
    "9": "Sep",
    "10": "Okt",
    "11": "Nov",
    "12": "Des"
  },
  {
    "1": "jan",
    "2": "feb",
    "3": "mar",
    "4": "apr",
    "5": "maí",
    "6": "jún",
    "7": "júl",
    "8": "ágú",
    "9": "sep",
    "10": "okt",
    "11": "nóv",
    "12": "des"
  }, {
    "1": "ene",
    "2": "feb",
    "3": "mar",
    "4": "abr",
    "5": "may",
    "6": "jun",
    "7": "jul",
    "8": "ago",
    "9": "sep",
    "10": "oct",
    "11": "nov",
    "12": "dic"
  },
  {
    "1": "gen",
    "2": "feb",
    "3": "mar",
    "4": "apr",
    "5": "mag",
    "6": "giu",
    "7": "lug",
    "8": "ago",
    "9": "set",
    "10": "ott",
    "11": "nov",
    "12": "dic"
  },
  {
    "1": "jan",
    "2": "feb",
    "3": "mar",
    "4": "apr",
    "5": "mai",
    "6": "jūn",
    "7": "jūl",
    "8": "aug",
    "9": "sep",
    "10": "okt",
    "11": "nov",
    "12": "dec"
  },
  {
    "1": "sau",
    "2": "vas",
    "3": "kov",
    "4": "bal",
    "5": "geg",
    "6": "bir",
    "7": "lie",
    "8": "rug",
    "9": "rus",
    "10": "spa",
    "11": "lap",
    "12": "gru"
  },
  {
    "1": "Jan",
    "2": "Feb",
    "3": "Mär",
    "4": "Apr",
    "5": "Mai",
    "6": "Jun",
    "7": "Jul",
    "8": "Aug",
    "9": "Sep",
    "10": "Okt",
    "11": "Nov",
    "12": "Dez"
  },
  {
    "1": "jan",
    "2": "feb",
    "3": "mar",
    "4": "apr",
    "5": "mai",
    "6": "jun",
    "7": "jul",
    "8": "aug",
    "9": "sep",
    "10": "okt",
    "11": "nov",
    "12": "des"
  },
  {
    "1": "sty",
    "2": "lut",
    "3": "mar",
    "4": "kwi",
    "5": "maj",
    "6": "cze",
    "7": "lip",
    "8": "sie",
    "9": "wrz",
    "10": "paź",
    "11": "lis",
    "12": "gru"
  },
  {
    "1": "jan",
    "2": "fev",
    "3": "mar",
    "4": "abr",
    "5": "mai",
    "6": "jun",
    "7": "jul",
    "8": "ago",
    "9": "set",
    "10": "out",
    "11": "nov",
    "12": "dez"
  },
  {
    "1": "ian",
    "2": "feb",
    "3": "mar",
    "4": "apr",
    "5": "mai",
    "6": "iun",
    "7": "iul",
    "8": "aug",
    "9": "sep",
    "10": "oct",
    "11": "noi",
    "12": "dec"
  },
  {
    "1": "Јан",
    "2": "Феб",
    "3": "Мар",
    "4": "Апр",
    "5": "Мај",
    "6": "Јун",
    "7": "Јул",
    "8": "Авг",
    "9": "Сеп",
    "10": "Окт",
    "11": "Нов",
    "12": "Дец"
  },
  {
    "1": "jan",
    "2": "feb",
    "3": "mar",
    "4": "apr",
    "5": "máj",
    "6": "jún",
    "7": "júl",
    "8": "aug",
    "9": "sep",
    "10": "okt",
    "11": "nov",
    "12": "dec"
  },
  {
    "1": "jan",
    "2": "feb",
    "3": "mar",
    "4": "apr",
    "5": "maj",
    "6": "jun",
    "7": "jul",
    "8": "avg",
    "9": "sep",
    "10": "okt",
    "11": "nov",
    "12": "dec"
  },
  {
    "1": "Oca",
    "2": "Şub",
    "3": "Mar",
    "4": "Nis",
    "5": "May",
    "6": "Haz",
    "7": "Tem",
    "8": "Ağu",
    "9": "Eyl",
    "10": "Eki",
    "11": "Kas",
    "12": "Ara"
  },
  {
    "1": "січ",
    "2": "лют",
    "3": "бер",
    "4": "кві",
    "5": "тра",
    "6": "чер",
    "7": "лип",
    "8": "сер",
    "9": "вер",
    "10": "жов",
    "11": "лис",
    "12": "гру"
  },
  {
    "1": "tam",
    "2": "hel",
    "3": "maa",
    "4": "huh",
    "5": "tou",
    "6": "kes",
    "7": "hei",
    "8": "elo",
    "9": "syy",
    "10": "lok",
    "11": "mar",
    "12": "jou"
  },
  {
    "1": "jan",
    "2": "fév",
    "3": "mar",
    "4": "avr",
    "5": "mai",
    "6": "jui",
    "7": "jui",
    "8": "aoû",
    "9": "sep",
    "10": "oct",
    "11": "nov",
    "12": "déc"
  },
  {
    "1": "led",
    "2": "úno",
    "3": "bře",
    "4": "dub",
    "5": "kvě",
    "6": "čer",
    "7": "čer",
    "8": "srp",
    "9": "zář",
    "10": "říj",
    "11": "lis",
    "12": "pro"
  },
  {
    "1": "jan",
    "2": "feb",
    "3": "mar",
    "4": "apr",
    "5": "maj",
    "6": "jun",
    "7": "jul",
    "8": "aug",
    "9": "sep",
    "10": "okt",
    "11": "nov",
    "12": "dec"
  },
  {
    "1": "jaa",
    "2": "vee",
    "3": "mär",
    "4": "apr",
    "5": "mai",
    "6": "juu",
    "7": "juu",
    "8": "aug",
    "9": "sep",
    "10": "okt",
    "11": "nov",
    "12": "det"
  },
  {
    "1": "יָנוּ",
    "2": "פֶבּר",
    "3": "מֶרץ",
    "4": "אַפּרִ",
    "5": "מַא",
    "6": "יוּנִ",
    "7": "יוּלִ",
    "8": "אוֹג",
    "9": "סֶפּטֶ",
    "10": "אוֹק",
    "11": "נוֹבֶ",
    "12": "דֶצֶמ"
  }
];
